name: Python Package using Conda

on:
  schedule:
    - cron: '0 22 * * *'   # UTC时间22:00（北京时间次日6:00）

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: base
        python-version: 3.10
        auto-activate-base: true
    - name: Lint with flake8
      run: |
        # 安装flake8到基础环境
        conda install -c conda-forge flake8 -y
        # 检查语法错误
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # 运行标准检查
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Install dependencies
      run: pip install -r ./requirements.txt
    - name: Run main script
      run: python ./main.py
    - name: Run main script
      continue-on-error: true  # 防止单个任务失败导致整个工作流失败
      run: python ./main.py
    - name: Cache Conda packages
      uses: actions/cache@v3
      env:
       CONDA_CACHE_DIR: /usr/share/miniconda3/pkgs
      with:
       path: ${{ env.CONDA_CACHE_DIR }}
       key: conda-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
