name: Python Package with Conda

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 22 * * *'   # UTC 22:00 (北京时间次日6:00)

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: '3.10'
        activate-environment: 'mihoyo-env'
    
    - name: Add conda to PATH
      run: |
        echo "$CONDA/bin" >> $GITHUB_PATH
        conda init bash
        source ~/.bashrc
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Run main program
      run: python ./main.py
